version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: simple_bank
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
    - 5432:5432
  simplebank:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - DATABASESOURCE=postgresql://root:root@postgres:5432/simple_bank?sslmode=disable
    container_name: simplebank
    depends_on:
    - postgres
    ports:
    - 8090:8090
    entrypoint:
    - /app/wait-for
    - postgres:5432
    - --
    - /app/start.sh
    command:
    - /app/main
    # depends_on:
    #   postgres:
    #     condition: service_healthy