version: '3.1'

services:
  postgres:
    networks:
      wave-net:
        aliases:
          - postgres
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
    - 5432:5432
networks:
  wave-net:
    external: true
